[package]
name = "fixit"
version = "0.4.0-beta"
edition = "2021"
license = "MIT"
authors = [ "Yevhenii Babichenko <eugene.babichenko@gmail.com>" ]
homepage = "https://github.com/eugene-babichenko/fixit"
repository = "https://github.com/eugene-babichenko/fixit"
readme = "README.md"
categories = [ "command-line-utilities" ]
description = "A utility to fix mistakes in your commands."

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
ctrlc = "3"
dialoguer = "0.11"
dirs = "5.0.1"
env_logger = "0.11"
indicatif = "0.17"
itertools = "0.13.0"
log = "0.4"
rayon = "1"
regex = "1"
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
strsim = "0.11"
thiserror = "1"
ureq = { version = "2.9.7", features = ["json"] }

[dev-dependencies]
httpmock = "0.7.0"
rstest = "0.21.0"
tempfile = "3.10.1"
