on:
  push:

name: Test makepkg on ubuntu

jobs:
  hello:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    steps:
      - run: |
          pacman --noconfirm -Syu
          pacman --noconfirm -S base-devel sudo git wget rust
          git clone --branch ${{ github.ref_name }} ${{ github.server_url }}/${{ github.repository }} fixit
          cd fixit
          sudo -u nobody ./packaging/aur.sh v0.3.1-beta
          cat PKGBUILD
          cat .SRCINFO
