on:
  push:

name: Test makepkg on ubuntu

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y makepkg && ./packaging/aur.sh v0.3.1-beta

