on:
  push:

name: Test makepkg on ubuntu

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker build -f ci/arch-build.dockerfile -t ci .
          docker run -v $PWD:/project -w /project ci sudo -u build -c 'bash -c ./packaging/aur.sh v0.3.1-beta'
          cat PKGBUILD
          cat .SRCINFO
