on:
  push:

name: Tests


jobs:
  fmt:
    name: Code formatters
    runs-on: ubuntu-latest
    steps:
      - name: Install Prettier
        run: npm install -g prettier

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run cargo fmt
        run: cargo fmt --check

      - name: Run Prettier
        run: prettier --check "**/*.{md,json,prettierrc}"

      - name: Run shellcheck
        run: shellcheck **/*.sh

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run cargo clippy
        run: cargo clippy --locked -- -D warnings

  tests:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        env:
          RUST_BACKTRACE: 1
        run: cargo test --locked
