on:
  push:

name: Tests

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-aur:
    name: Update AUR repositories
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    strategy:
      matrix:
        include:
          - bin: ""
          - bin: "-bin"
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm rust openssh git

      - name: Checkout
        uses: actions/checkout@v4

      - name: Update AUR
        run: |
          VERSION=0.7.0

          cargo xtask packaging $VERSION aur${{matrix.bin}}

          mkdir -p ~/.ssh
          echo "${{ secrets.AUR_SSH_PRIVATE_KEY }}" > ~/.ssh/aur
          chmod 600 ~/.ssh/aur
          echo "Host aur.archlinux.org" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/aur" >> ~/.ssh/config
          echo "  User aur" >> ~/.ssh/config
          ssh-keyscan -H aur.archlinux.org >> ~/.ssh/known_hosts

          git clone ssh://aur@aur.archlinux.org/fixit${{ matrix.bin }}.git aur
          cp PKGBUILD .SRCINFO aur/
          cd aur
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add PKGBUILD .SRCINFO
          git commit -m "chore: release $VERSION"
          git push --dry-run origin master

  fmt:
    name: Code formatters
    runs-on: ubuntu-latest
    steps:
      - name: Install Prettier
        run: npm install -g prettier

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run cargo fmt
        run: cargo fmt --check

      - name: Run Prettier
        run: prettier --check "**/*.{md,json,prettierrc}"

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo clippy
        run: cargo clippy --locked

  tests:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        env:
          RUST_BACKTRACE: 1
        run: cargo test --locked

  audit:
    name: Check security advisory database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo-audit
        run: |
          gh release download --repo rustsec/rustsec --pattern 'cargo-audit-x86_64-unknown-linux-musl-*.tgz'
          tar -xvzf cargo-audit-x86_64-unknown-linux-musl-*.tgz
          cp cargo-audit-x86_64-unknown-linux-musl-*/cargo-audit .
          ./cargo-audit audit

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo-tarpaulin
        run: |
          gh release download --repo xd009642/tarpaulin --pattern 'cargo-tarpaulin-x86_64-unknown-linux-musl.tar.gz'
          tar -xvzf cargo-tarpaulin-x86_64-unknown-linux-musl.tar.gz
          ./cargo-tarpaulin --skip-clean --coveralls ${{ secrets.COVERALLS_TOKEN }}
