on:
  push:

name: Tests

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  fmt:
    name: Code formatters
    runs-on: ubuntu-latest
    steps:
      - name: Install Prettier
        run: npm install -g prettier

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run cargo fmt
        run: cargo fmt --check

      - name: Run Prettier
        run: prettier --check "**/*.{md,json,prettierrc}"

  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo clippy
        run: cargo clippy --locked

  tests:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        env:
          RUST_BACKTRACE: 1
        run: cargo test --locked

  audit:
    name: Check security advisory database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo-audit
        run: |
          gh release download --repo rustsec/rustsec --pattern 'cargo-audit-x86_64-unknown-linux-musl-*.tgz'
          tar -xvzf cargo-audit-x86_64-unknown-linux-musl-*.tgz
          cp cargo-audit-x86_64-unknown-linux-musl-*/cargo-audit .
          ./cargo-audit audit

  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo-tarpaulin
        run: |
          gh release download --repo xd009642/tarpaulin --pattern 'cargo-tarpaulin-x86_64-unknown-linux-musl.tar.gz'
          tar -xvzf cargo-tarpaulin-x86_64-unknown-linux-musl.tar.gz
          ./cargo-tarpaulin --follow-exec --skip-clean --coveralls ${{ secrets.COVERALLS_TOKEN }}
